version: 2

aliases:
  - &restore-cache
    restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
  - &install-deps
    run:
        name: Install dependencies
        command: npm ci
  - &build-packages
    run:
        name: Build
        command: npm run build

jobs:
  build:
    working_directory: ~/nest
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: Update NPM version
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: npm run build    
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run : echo "hello abdo" > ~/abdo.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - abdo.txt
  print_output:
        docker:
        - image: circleci/node:13.8.0 
        steps:
          - attach_workspace:
              at: ~/
          - run : cat ~/abdo.txt
                
  integration_tests:
    working_directory: ~/nest
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - *restore-cache
      - *install-deps
      - run:
          name: Integration tests
          command: npm run test:integration

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - save_hello_world_output
      - print_output:
          requires:
            - save_hello_world_output